### author by yangshichen
### 注意：脚本仅供参考，使用前请仔细阅读

In [1]:
import os
import scanpy as sc
import anndata as ad
import numpy as np
import pandas as pd
import seaborn as sb
import seaborn as sns
from matplotlib.pyplot import rc_context
import matplotlib.pyplot as plt
from scipy.io import mmread
from scipy.sparse import csr_matrix
import matplotlib as mpl
mpl.rcParams['pdf.fonttype'] = 42
from scipy.sparse import issparse
import decoupler as dc
from sklearn.preprocessing import QuantileTransformer
from multiprocessing import Pool, cpu_count
from functools import partial
from sklearn.preprocessing import QuantileTransformer, StandardScaler
quantile_transformer = QuantileTransformer(output_distribution='normal', random_state=0)
scaler = StandardScaler()

import warnings
warnings.filterwarnings("ignore")

In [2]:
sc.settings.verbosity = 3             # verbosity: errors (0), warnings (1), info (2), hints (3)
sc.logging.print_header()
sc.settings.set_figure_params(dpi=100, frameon=False)
sc._settings.ScanpyConfig.n_jobs=70

scanpy==1.9.8 anndata==0.9.2 umap==0.5.7 numpy==1.24.4 scipy==1.10.1 pandas==2.0.3 scikit-learn==1.3.2 statsmodels==0.14.1 pynndescent==0.5.13

In [3]:
import os
os.environ["R_HOME"] = "/home/yangshichen//mambaforge/envs/QTL/lib/R"
os.environ["R_LIBS_USER"] = "/home/yangshichen/mambaforge/envs/QTL/lib/R/library"
import pandas as pd
import torch
import tensorqtl
from tensorqtl import  cis
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"torch: {torch.__version__} (CUDA {torch.version.cuda}), device: {device}")
print(f"pandas: {pd.__version__}")

Warning: 'rfunc' cannot be imported. R with the 'qvalue' library and the 'rpy2' Python package are needed to compute q-values.
torch: 2.4.1+cu121 (CUDA 12.1), device: cpu
pandas: 2.0.3

### Use tensorqtl-eQTL

#### Gene expression.csv转bed

In [4]:
# 输入目录、输出目录
input_dir = "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Data/scRNA-seq/02.normal_dis/"
output_dir1 = "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Data/scRNA-seq/06.gene_expression_bed/"
output_dir2 = "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Data/scRNA-seq/07.gene_expression_csv/"

# 基因注释表（必须包含 gene_id, chrom, start, end）
annotation_df = pd.read_csv("/media/AnalysisDisk2/Yangshichen/0_HIV_RNA/QTL/Data/Genotype/gene_annotation.txt", sep='\t')
annotation_df = annotation_df.rename(columns={
    "gene_id": "gene_id",
    "chr": "chr",
    "left": "start",
    "right": "end"})
annotation_df

           gene_id   chr     start       end
0         DDX11L17  chr1    182696    184174
1           PRDM16  chr1   3069168   3438621
2            PEX10  chr1   2403964   2413797
3         RPL21P21  chr1  10054445  10054781
4        LINC01345  chr1   3944547   3949024
...            ...   ...       ...       ...
41008    ZNF736P9Y  chrY   8068896   8070723
41009     FAM197Y8  chrY   9354846   9356814
41010         PRKY  chrY   7274313   7371868
41011  SEPTIN14P23  chrY  25378300  25394719
41012     FAM41AY2  chrY  18390994  18405046

[41013 rows x 4 columns]

In [5]:
import pandas as pd
import re
def chrom_sort_key(chrom):
    # 提取数字部分（chr1 → 1, chrX → 23, chrY → 24）
    match = re.match(r'chr(\d+)$', chrom)
    if match:
        return int(match.group(1))
    elif chrom == 'chrX':
        return 23
    elif chrom == 'chrY':
        return 24
    elif chrom == 'chrM':
        return 25
    else:
        return 100  # 把奇怪的染色体排到后面

In [6]:
#遍历所有csv文件
for fname in os.listdir(input_dir):
    if fname.endswith(".csv"):
        print("Processing:", fname)
        expr_df = pd.read_csv(os.path.join(input_dir, fname), index_col=0).T
        expr_df.index.name = 'gene_id'
        expr_df.reset_index(inplace=True)

        #合并注释
        merged_df = annotation_df.merge(expr_df, on='gene_id')
        merged_df = merged_df[['chr', 'start', 'end', 'gene_id'] + list(expr_df.columns[1:])]

        #按照染色体顺序排序（否则会报错）
        autosomes = [f"chr{i}" for i in range(1, 23)]
        merged_df = merged_df[merged_df["chr"].isin(autosomes)]
        merged_df['chr_sort_key'] = merged_df['chr'].apply(chrom_sort_key)
        merged_df = merged_df.sort_values(by=['chr_sort_key', 'start', 'end']).drop(columns='chr_sort_key').reset_index(drop=True)

        #保存为bed和csv格式
        bed_fname = fname.replace(".csv", ".bed")
        merged_df.to_csv(os.path.join(output_dir1, bed_fname), sep='\t', index=False)
        merged_df.to_csv(os.path.join(output_dir2, fname), index=False)
        print("Processing:", fname, "Done!")

Processing: Adaptive NK cells.csv
Processing: Adaptive NK cells.csv Done!
Processing: ALPL- MARCKS- NDNs.csv
Processing: ALPL- MARCKS- NDNs.csv Done!
Processing: ASDC.csv
Processing: ASDC.csv Done!
Processing: Atypical naïve B cells.csv
Processing: Atypical naïve B cells.csv Done!
Processing: Basophils.csv
Processing: Basophils.csv Done!
Processing: CCR4+ CD8+ Tcm.csv
Processing: CCR4+ CD8+ Tcm.csv Done!
Processing: CCR4- CD8+ Tcm.csv
Processing: CCR4- CD8+ Tcm.csv Done!
Processing: CD14+ cDC2.csv
Processing: CD14+ cDC2.csv Done!
Processing: CD177int iLDNs.csv
Processing: CD177int iLDNs.csv Done!
Processing: CD1C+ cDC2.csv
Processing: CD1C+ cDC2.csv Done!
Processing: CD27+ IgD+ atypical memory B cells.csv
Processing: CD27+ IgD+ atypical memory B cells.csv Done!
Processing: CD27+ IgD- atypical memory B cells.csv
Processing: CD27+ IgD- atypical memory B cells.csv Done!
Processing: CD27+ MAIT.csv
Processing: CD27+ MAIT.csv Done!
Processing: CD27+ Th1.csv
Processing: CD27+ Th1.csv Done!
Processing: CD27+ Th17.csv
Processing: CD27+ Th17.csv Done!
Processing: CD27- IgD- atypical memory B cells.csv
Processing: CD27- IgD- atypical memory B cells.csv Done!
Processing: CD27- MAIT.csv
Processing: CD27- MAIT.csv Done!
Processing: CD27- Th1.csv
Processing: CD27- Th1.csv Done!
Processing: CD27- Th17.csv
Processing: CD27- Th17.csv Done!
Processing: CD279+ SOX4+ Vδ1+ T cells.csv
Processing: CD279+ SOX4+ Vδ1+ T cells.csv Done!
Processing: CD4+ Temra.csv
Processing: CD4+ Temra.csv Done!
Processing: CD56+ MAIT.csv
Processing: CD56+ MAIT.csv Done!
Processing: CD56bright NK cells.csv
Processing: CD56bright NK cells.csv Done!
Processing: CD56dim NK cells.csv
Processing: CD56dim NK cells.csv Done!
Processing: CD62Lhi GZMK+ Vδ2+ T cells.csv
Processing: CD62Lhi GZMK+ Vδ2+ T cells.csv Done!
Processing: CD8+ Temra.csv
Processing: CD8+ Temra.csv Done!
Processing: CD8+ Treg.csv
Processing: CD8+ Treg.csv Done!
Processing: CD95 memory B cells.csv
Processing: CD95 memory B cells.csv Done!
Processing: cDC1.csv
Processing: cDC1.csv Done!
Processing: CILCP.csv
Processing: CILCP.csv Done!
Processing: CLP.csv
Processing: CLP.csv Done!
Processing: Core classical monocytes.csv
Processing: Core classical monocytes.csv Done!
Processing: CXCL8- PTGS2+ NDNs.csv
Processing: CXCL8- PTGS2+ NDNs.csv Done!
Processing: DN T cells.csv
Processing: DN T cells.csv Done!
Processing: Early memory B cells.csv
Processing: Early memory B cells.csv Done!
Processing: FOS- NDNs.csv
Processing: FOS- NDNs.csv Done!
Processing: GBP1+ classical monocytes.csv
Processing: GBP1+ classical monocytes.csv Done!
Processing: GZMB+ CD4+ terminal effector T cells.csv
Processing: GZMB+ CD4+ terminal effector T cells.csv Done!
Processing: GZMB+ CD8+ Tem.csv
Processing: GZMB+ CD8+ Tem.csv Done!
Processing: GZMB+ Vδ2+ T cells.csv
Processing: GZMB+ Vδ2+ T cells.csv Done!
Processing: GZMK+ CD8+ Tem.csv
Processing: GZMK+ CD8+ Tem.csv Done!
Processing: GZMK+ effector Vδ1+ T cells.csv
Processing: GZMK+ effector Vδ1+ T cells.csv Done!
Processing: GZMK+ Vδ2+ T cells.csv
Processing: GZMK+ Vδ2+ T cells.csv Done!
Processing: HLA-DRhi CD4+ terminal effector T cells.csv
Processing: HLA-DRhi CD4+ terminal effector T cells.csv Done!
Processing: HLA-DRhi CD4+ Treg.csv
Processing: HLA-DRhi CD4+ Treg.csv Done!
Processing: HLA-DRhi CD8+ Tem.csv
Processing: HLA-DRhi CD8+ Tem.csv Done!
Processing: HSC_MPP.csv
Processing: HSC_MPP.csv Done!
Processing: IGKChi Plasma cells.csv
Processing: IGKChi Plasma cells.csv Done!
Processing: IGLL5hi Plasma cells.csv
Processing: IGLL5hi Plasma cells.csv Done!
Processing: ILC2.csv
Processing: ILC2.csv Done!
Processing: ILCP.csv
Processing: ILCP.csv Done!
Processing: iNKT.csv
Processing: iNKT.csv Done!
Processing: Intermediate monocytes.csv
Processing: Intermediate monocytes.csv Done!
Processing: IRF1- GBP2- NDNs.csv
Processing: IRF1- GBP2- NDNs.csv Done!
Processing: ISG+ classical monocytes.csv
Processing: ISG+ classical monocytes.csv Done!
Processing: KLRB1+ CD4+ Treg.csv
Processing: KLRB1+ CD4+ Treg.csv Done!
Processing: KLRC2+ effector Vδ1+ T cells.csv
Processing: KLRC2+ effector Vδ1+ T cells.csv Done!
Processing: LAMP3+ DC.csv
Processing: LAMP3+ DC.csv Done!
Processing: MC_MCP.csv
Processing: MC_MCP.csv Done!
Processing: Memory CD4+ Treg.csv
Processing: Memory CD4+ Treg.csv Done!
Processing: MEP.csv
Processing: MEP.csv Done!
Processing: MkP.csv
Processing: MkP.csv Done!
Processing: MMP8+ CD177+ iLDNs.csv
Processing: MMP8+ CD177+ iLDNs.csv Done!
Processing: MMP8+ CD177+ mLDNs.csv
Processing: MMP8+ CD177+ mLDNs.csv Done!
Processing: MPO+ CD177- iLDNs.csv
Processing: MPO+ CD177- iLDNs.csv Done!
Processing: MPO+ mLDNs.csv
Processing: MPO+ mLDNs.csv Done!
Processing: MPO- CD177- iLDNs.csv
Processing: MPO- CD177- iLDNs.csv Done!
Processing: MT-ATP6- MT-CO2- NDNs.csv
Processing: MT-ATP6- MT-CO2- NDNs.csv Done!
Processing: Naïve B cells.csv
Processing: Naïve B cells.csv Done!
Processing: Naïve CD4+ T cells.csv
Processing: Naïve CD4+ T cells.csv Done!
Processing: Naïve CD4+ Treg.csv
Processing: Naïve CD4+ Treg.csv Done!
Processing: Naïve CD8+ T cells.csv
Processing: Naïve CD8+ T cells.csv Done!
Processing: Naïve Vδ1+ T cells.csv
Processing: Naïve Vδ1+ T cells.csv Done!
Processing: Non-classical monocytes.csv
Processing: Non-classical monocytes.csv Done!
Processing: Non-switched memory B cells.csv
Processing: Non-switched memory B cells.csv Done!
Processing: pDCs.csv
Processing: pDCs.csv Done!
Processing: Plamsablasts.csv
Processing: Plamsablasts.csv Done!
Processing: Platelets.csv
Processing: Platelets.csv Done!
Processing: Proliferative CD4+ Treg.csv
Processing: Proliferative CD4+ Treg.csv Done!
Processing: Core NDNs.csv
Processing: Core NDNs.csv Done!
Processing: IFIT2- RNF213- NDNs.csv
Processing: IFIT2- RNF213- NDNs.csv Done!
Processing: MMP9+ CD177+ iLDNs.csv
Processing: MMP9+ CD177+ iLDNs.csv Done!
Processing: Proliferative CD8+ memory T cells.csv
Processing: Proliferative CD8+ memory T cells.csv Done!
Processing: Proliferative cytotoxic CD4+ T cells.csv
Processing: Proliferative cytotoxic CD4+ T cells.csv Done!
Processing: Proliferative DN T cells.csv
Processing: Proliferative DN T cells.csv Done!
Processing: Proliferative help memory T cells.csv
Processing: Proliferative help memory T cells.csv Done!
Processing: Proliferative iLDNs.csv
Processing: Proliferative iLDNs.csv Done!
Processing: Proliferative mLDNs.csv
Processing: Proliferative mLDNs.csv Done!
Processing: Proliferative NK cells.csv
Processing: Proliferative NK cells.csv Done!
Processing: Proliferative Vδ2+ T cells.csv
Processing: Proliferative Vδ2+ T cells.csv Done!
Processing: RGS2- NDNs.csv
Processing: RGS2- NDNs.csv Done!
Processing: SOX4+ Vδ1+ T cells.csv
Processing: SOX4+ Vδ1+ T cells.csv Done!
Processing: Switched Memory B cells.csv
Processing: Switched Memory B cells.csv Done!
Processing: Tfh.csv
Processing: Tfh.csv Done!
Processing: Th1_Th17.csv
Processing: Th1_Th17.csv Done!
Processing: Th2.csv
Processing: Th2.csv Done!
Processing: Th22.csv
Processing: Th22.csv Done!
Processing: VIM- FLNA- NDNs.csv
Processing: VIM- FLNA- NDNs.csv Done!
Processing: vNKT.csv
Processing: vNKT.csv Done!

In [7]:
merged_df

,chr,start,end,gene_id,HP-253,HP-778,HP-263,HP-431,HP-869,HP-111,...,HP-89,HP-384,HP-639,HP-697,HP-283,HP-237,HP-282,HP-404,HP-262,HP-825
0,chr1,825138,859446,LINC01128,0.699345,0.436828,-1.887016,1.105567,0.728943,1.280193,...,-1.887016,1.345523,-1.887016,1.024452,0.195584,0.880230,0.146236,0.601588,-1.887016,0.455934
1,chr1,944203,959309,NOC2L,0.514083,0.106399,0.498417,0.851569,-0.241444,-3.299698,...,-3.299698,0.945597,1.214452,-0.450254,0.232667,0.124648,0.220339,0.212140,0.398398,0.120593
2,chr1,960584,965719,KLHL17,0.172558,-1.761082,-1.761082,-1.761082,0.117145,-1.761082,...,-1.761082,0.360170,0.906860,0.172558,0.888675,0.495955,0.621252,1.126121,-1.761082,0.615082
3,chr1,1001138,1014540,ISG15,-0.078250,-0.474597,0.503714,1.185523,-0.662264,0.503714,...,1.504617,-0.051069,-0.351765,-0.563323,-0.566723,-0.029380,-0.296077,-0.951954,-0.048355,-0.418243
4,chr1,1081818,1116361,C1orf159,1.136246,0.202413,-1.926320,0.473467,0.489175,-1.926320,...,-1.926320,-1.926320,0.473467,0.121069,0.255582,-0.034023,0.289105,0.206556,1.247201,0.362476
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8508,chr22,50525752,50530032,TYMP,-0.401659,-0.665902,-0.591141,0.136790,-0.339752,-3.473521,...,-3.473521,-0.957286,0.838976,-0.042517,0.043358,0.504016,-0.794035,-0.142019,0.655034,0.343038
8509,chr22,50568861,50578465,CPT1B,-0.107367,0.785424,1.182466,-2.177783,0.429245,-2.177783,...,-2.177783,0.120724,0.193813,0.111563,-0.207714,0.588637,0.476276,-2.177783,-2.177783,0.386776
8510,chr22,50578959,50601455,CHKB,0.827567,0.399443,0.343856,-0.444998,-0.388123,-4.293165,...,0.864352,-1.021685,-0.304931,-0.960671,-0.871046,0.947805,0.016035,0.898447,0.728951,0.244254
8511,chr22,50622754,50628173,ARSA,0.036472,-0.469039,-0.415253,-0.003008,-0.121544,-3.581796,...,3.770405,0.071411,0.398842,-0.911205,0.515833,-0.377804,0.097574,-0.496412,-0.550704,0.287421
8512,chr22,50767501,50783667,RABL2B,0.397559,-0.433191,-0.855820,-3.255205,0.155256,1.164501,...,-3.255205,1.463370,-0.504607,-0.144820,-0.061682,0.147233,-0.471809,0.369348,1.214379,0.419612

#### Read genotype_df and vatiant_df

In [8]:
genotype_df = pd.read_parquet('/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Data/Genetics/WGS_HP_genotype.parquet')
variant_df = pd.read_parquet('/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Data/Genetics/WGS_HP_variant_df.parquet')
variant_df['chrom'] = 'chr' + variant_df['chrom'].astype(str)

#### Run tensorqtl

In [9]:
#设置bed文件所在的文件夹路径
bed_dir = '/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Data/scRNA-seq/06.gene_expression_bed/'
output_dir = '/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL/'

#获取所有以.bed结尾的文件
bed_files = [f for f in os.listdir(bed_dir) if f.endswith('.bed')]

In [10]:
len(bed_files)

99

In [11]:
# 遍历文件，处理并创建对应文件夹
for bed_file in bed_files:
    cell_name = os.path.splitext(bed_file)[0]  # 去掉.bed后缀
    folder_path = os.path.join(output_dir, cell_name)
    os.makedirs(folder_path, exist_ok=True)  # 创建文件夹

    #read_expression_file and covariates
    expression_bed = f'/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Data/scRNA-seq/06.gene_expression_bed/{cell_name}.bed'
    covariates_file = f'/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Data/scRNA-seq/05.PEER/01.factor/{cell_name}.csv'

    #load phenotypes and covariates
    #align phenotypes and covariates
    phenotype_df, phenotype_pos_df = tensorqtl.read_phenotype_bed(expression_bed)
    covariates_df = pd.read_csv(covariates_file, sep=',', index_col=0)
    phenotype_df = phenotype_df[covariates_df.index]

    #decited the number of peer factor
    sample_size = covariates_df.shape[0]
    if sample_size <= 150:
        PF = list('PF' + str(i) for i in range(1, 16))
    elif sample_size <= 250:
        PF = list('PF' + str(i) for i in range(1, 31))
    elif sample_size <= 350:
        PF = list('PF' + str(i) for i in range(1, 46))
    elif sample_size > 350:
        PF = list('PF' + str(i) for i in range(1, 61))
        info = list(['Gender', 'Age', 'Batch', 'Pregnancy', 'PC1', 'PC2'])
        cova_need = info + PF
        covariates_df = covariates_df.loc[:,cova_need]

    #cis-QTL mapping: permutations (对每个基因，寻找在附近（cis-window，一般是±1Mb）的SNP是否与其表达量显著相关。)
    cis_df = cis.map_cis(genotype_df, variant_df, phenotype_df, phenotype_pos_df, covariates_df, 
                         maf_threshold=0.1, seed=8888)

    #后续统一再在py里面算（环境问题）
    #tensorqtl.calculate_qvalues(cis_df)

    #保存
    cis_df.to_csv(f'{folder_path}/all_lead_perm.csv')

    #cis-QTL mapping: summary statistics for all variant-phenotype pairs（所有变异-表型对的统计汇总）
    cis.map_nominal(genotype_df, variant_df, phenotype_df, phenotype_pos_df, 'all', covariates_df, maf_threshold=0.1, 
                    output_dir=f'{folder_path}')

cis-QTL mapping: empirical p-values for phenotypes
  * 815 samples
  * 13189 phenotypes
  * 66 covariates
  * 6990104 variants
  * applying in-sample 0.1 MAF filter
  * cis-window: ±1,000,000
  * using seed 8888
  * checking phenotypes: 13189/13189
    ** dropping 1340 phenotypes without variants in cis-window
  * computing permutations
    processing phenotype 11849/11849
  Time elapsed: 36.91 min
done.
cis-QTL mapping: nominal associations for all variant-phenotype pairs
  * 815 samples
  * 13189 phenotypes
  * 66 covariates
  * 6990104 variants
  * applying in-sample 0.1 MAF filter
  * cis-window: ±1,000,000
  * checking phenotypes: 13189/13189
    ** dropping 1340 phenotypes without variants in cis-window
  * Computing associations
    Mapping chromosome chr1
    processing phenotype 600/11849    time elapsed: 0.17 min
    * writing output
    Mapping chromosome chr2
    processing phenotype 1513/11849    time elapsed: 0.45 min
    * writing output
    Mapping chromosome chr3
    processing phenotype 2279/11849    time elapsed: 0.69 min
    * writing output
    Mapping chromosome chr4
    processing phenotype 2581/11849    time elapsed: 0.81 min
    * writing output
    Mapping chromosome chr5
    processing phenotype 3046/11849    time elapsed: 0.95 min
    * writing output
    Mapping chromosome chr6
    processing phenotype 3786/11849    time elapsed: 1.50 min
    * writing output
    Mapping chromosome chr7
    processing phenotype 4442/11849    time elapsed: 1.73 min
    * writing output
    Mapping chromosome chr8
    processing phenotype 4889/11849    time elapsed: 1.88 min
    * writing output
    Mapping chromosome chr9
    processing phenotype 5431/11849    time elapsed: 2.03 min
    * writing output
    Mapping chromosome chr10
    processing phenotype 5733/11849    time elapsed: 2.15 min
    * writing output
    Mapping chromosome chr11
    processing phenotype 6495/11849    time elapsed: 2.34 min
    * writing output
    Mapping chromosome chr12
    processing phenotype 7252/11849    time elapsed: 2.55 min
    * writing output
    Mapping chromosome chr13
    processing phenotype 7461/11849    time elapsed: 2.65 min
    * writing output
    Mapping chromosome chr14
    processing phenotype 7935/11849    time elapsed: 2.80 min
    * writing output
    Mapping chromosome chr15
    processing phenotype 8362/11849    time elapsed: 2.95 min
    * writing output
    Mapping chromosome chr16
    processing phenotype 8978/11849    time elapsed: 3.12 min
    * writing output
    Mapping chromosome chr17
    processing phenotype 9788/11849    time elapsed: 3.40 min
    * writing output
    Mapping chromosome chr18
    processing phenotype 9969/11849    time elapsed: 3.48 min
    * writing output
    Mapping chromosome chr19
    processing phenotype 10993/11849    time elapsed: 3.74 min
    * writing output
    Mapping chromosome chr20
    processing phenotype 11363/11849    time elapsed: 3.89 min
    * writing output
    Mapping chromosome chr21
    processing phenotype 11503/11849    time elapsed: 3.94 min
    * writing output
    Mapping chromosome chr22
    processing phenotype 11849/11849
    time elapsed: 4.02 min
    * writing output
done.
cis-QTL mapping: empirical p-values for phenotypes
  * 845 samples
  * 12123 phenotypes
  * 66 covariates
  * 6990104 variants
  * applying in-sample 0.1 MAF filter
  * cis-window: ±1,000,000
  * using seed 8888
  * checking phenotypes: 12123/12123
    ** dropping 1254 phenotypes without variants in cis-window
  * computing permutations
    processing phenotype 10869/10869
  Time elapsed: 35.56 min
done.
cis-QTL mapping: nominal associations for all variant-phenotype pairs
  * 845 samples
  * 12123 phenotypes
  * 66 covariates
  * 6990104 variants
  * applying in-sample 0.1 MAF filter
  * cis-window: ±1,000,000
  * checking phenotypes: 12123/12123
    ** dropping 1254 phenotypes without variants in cis-window
  * Computing associations
    Mapping chromosome chr1
    processing phenotype 532/10869    time elapsed: 0.11 min
    * writing output
    Mapping chromosome chr2
    processing phenotype 1392/10869    time elapsed: 0.37 min
    * writing output
    Mapping chromosome chr3
    processing phenotype 2129/10869    time elapsed: 0.64 min
    * writing output
    Mapping chromosome chr4
    processing phenotype 2421/10869    time elapsed: 0.78 min
    * writing output
    Mapping chromosome chr5
    processing phenotype 2839/10869    time elapsed: 0.93 min
    * writing output
    Mapping chromosome chr6
    processing phenotype 3521/10869    time elapsed: 1.35 min
    * writing output
    Mapping chromosome chr7
    processing phenotype 4117/10869    time elapsed: 1.60 min
    * writing output
    Mapping chromosome chr8
    processing phenotype 4537/10869    time elapsed: 1.88 min
    * writing output
    Mapping chromosome chr9
    processing phenotype 5026/10869    time elapsed: 2.08 min
    * writing output
    Mapping chromosome chr10
    processing phenotype 5292/10869    time elapsed: 2.21 min
    * writing output
    Mapping chromosome chr11
    processing phenotype 6003/10869    time elapsed: 2.39 min
    * writing output
    Mapping chromosome chr12
    processing phenotype 6696/10869    time elapsed: 2.61 min
    * writing output
    Mapping chromosome chr13
    processing phenotype 6893/10869    time elapsed: 2.73 min
    * writing output
    Mapping chromosome chr14
    processing phenotype 7331/10869    time elapsed: 2.87 min
    * writing output
    Mapping chromosome chr15
    processing phenotype 7714/10869    time elapsed: 3.02 min
    * writing output
    Mapping chromosome chr16
    processing phenotype 8284/10869    time elapsed: 3.23 min
    * writing output
    Mapping chromosome chr17
    processing phenotype 9027/10869    time elapsed: 3.47 min
    * writing output
    Mapping chromosome chr18
    processing phenotype 9189/10869    time elapsed: 3.60 min
    * writing output
    Mapping chromosome chr19
    processing phenotype 10094/10869    time elapsed: 3.86 min
    * writing output
    Mapping chromosome chr20
    processing phenotype 10424/10869    time elapsed: 4.02 min
    * writing output
    Mapping chromosome chr21
    processing phenotype 10551/10869    time elapsed: 4.08 min
    * writing output
    Mapping chromosome chr22
    processing phenotype 10869/10869
    time elapsed: 4.17 min
    * writing output
done.
cis-QTL mapping: empirical p-values for phenotypes
  * 781 samples
  * 2289 phenotypes
  * 66 covariates
  * 6990104 variants
  * applying in-sample 0.1 MAF filter
  * cis-window: ±1,000,000
  * using seed 8888
  * checking phenotypes: 2289/2289
    ** dropping 227 phenotypes without variants in cis-window
  * computing permutations
    processing phenotype 2062/2062
  Time elapsed: 6.13 min
done.
cis-QTL mapping: nominal associations for all variant-phenotype pairs
  * 781 samples
  * 2289 phenotypes
  * 66 covariates
  * 6990104 variants
  * applying in-sample 0.1 MAF filter
  * cis-window: ±1,000,000
  * checking phenotypes: 2289/2289
    ** dropping 227 phenotypes without variants in cis-window
  * Computing associations
    Mapping chromosome chr1
    processing phenotype 110/2062    time elapsed: 0.02 min
    * writing output
    Mapping chromosome chr2
    processing phenotype 273/2062    time elapsed: 0.06 min
    * writing output
    Mapping chromosome chr3
    processing phenotype 399/2062    time elapsed: 0.10 min
    * writing output
    Mapping chromosome chr4
    processing phenotype 447/2062    time elapsed: 0.12 min
    * writing output
    Mapping chromosome chr5
    processing phenotype 528/2062    time elapsed: 0.14 min
    * writing output
    Mapping chromosome chr6
    processing phenotype 660/2062    time elapsed: 0.28 min
    * writing output
    Mapping chromosome chr7
    processing phenotype 769/2062    time elapsed: 0.33 min
    * writing output
    Mapping chromosome chr8
    processing phenotype 830/2062    time elapsed: 0.36 min
    * writing output
    Mapping chromosome chr9
    processing phenotype 905/2062    time elapsed: 0.38 min
    * writing output
    Mapping chromosome chr10
    processing phenotype 957/2062    time elapsed: 0.41 min
    * writing output
    Mapping chromosome chr11
    processing phenotype 1114/2062    time elapsed: 0.45 min
    * writing output
    Mapping chromosome chr12
    processing phenotype 1252/2062    time elapsed: 0.56 min
    * writing output
    Mapping chromosome chr13
    processing phenotype 1287/2062    time elapsed: 0.58 min
    * writing output
    Mapping chromosome chr14
    processing phenotype 1368/2062    time elapsed: 0.60 min
    * writing output
    Mapping chromosome chr15
    processing phenotype 1445/2062    time elapsed: 0.63 min
    * writing output
    Mapping chromosome chr16
    processing phenotype 1538/2062    time elapsed: 0.66 min
    * writing output
    Mapping chromosome chr17
    processing phenotype 1682/2062    time elapsed: 0.70 min
    * writing output
    Mapping chromosome chr18
    processing phenotype 1711/2062    time elapsed: 0.73 min
    * writing output
    Mapping chromosome chr19
    processing phenotype 1907/2062    time elapsed: 0.78 min
    * writing output
    Mapping chromosome chr20
    processing phenotype 1979/2062    time elapsed: 0.81 min
    * writing output
    Mapping chromosome chr21
    processing phenotype 2002/2062    time elapsed: 0.83 min
    * writing output
    Mapping chromosome chr22
    processing phenotype 2062/2062
    time elapsed: 0.84 min
    * writing output
done.
cis-QTL mapping: empirical p-values for phenotypes
  * 793 samples
  * 1156 phenotypes
  * 66 covariates
  * 6990104 variants
  * applying in-sample 0.1 MAF filter
  * cis-window: ±1,000,000
  * using seed 8888
  * checking phenotypes: 1156/1156
    ** dropping 115 phenotypes without variants in cis-window
  * computing permutations
    processing phenotype 1041/1041
  Time elapsed: 3.35 min
done.
cis-QTL mapping: nominal associations for all variant-phenotype pairs
  * 793 samples
  * 1156 phenotypes
  * 66 covariates
  * 6990104 variants
  * applying in-sample 0.1 MAF filter
  * cis-window: ±1,000,000
  * checking phenotypes: 1156/1156
    ** dropping 115 phenotypes without variants in cis-window
  * Computing associations
    Mapping chromosome chr1
    processing phenotype 60/1041    time elapsed: 0.01 min
    * writing output
    Mapping chromosome chr2
    processing phenotype 144/1041    time elapsed: 0.04 min
    * writing output
    Mapping chromosome chr3
    processing phenotype 203/1041    time elapsed: 0.06 min
    * writing output
    Mapping chromosome chr4
    processing phenotype 225/1041    time elapsed: 0.07 min
    * writing output
    Mapping chromosome chr5
    processing phenotype 264/1041    time elapsed: 0.08 min
    * writing output
    Mapping chromosome chr6
    processing phenotype 341/1041    time elapsed: 0.17 min
    * writing output
    Mapping chromosome chr7
    processing phenotype 389/1041    time elapsed: 0.19 min
    * writing output
    Mapping chromosome chr8
    processing phenotype 422/1041    time elapsed: 0.20 min
    * writing output
    Mapping chromosome chr9
    processing phenotype 461/1041    time elapsed: 0.21 min
    * writing output
    Mapping chromosome chr10
    processing phenotype 489/1041    time elapsed: 0.22 min
    * writing output
    Mapping chromosome chr11
    processing phenotype 561/1041    time elapsed: 0.24 min
    * writing output
    Mapping chromosome chr12
    processing phenotype 635/1041    time elapsed: 0.26 min
    * writing output
    Mapping chromosome chr13
    processing phenotype 657/1041    time elapsed: 0.27 min
    * writing output
    Mapping chromosome chr14
    processing phenotype 701/1041    time elapsed: 0.29 min
    * writing output
    Mapping chromosome chr15
    processing phenotype 734/1041    time elapsed: 0.30 min
    * writing output
    Mapping chromosome chr16
    processing phenotype 780/1041    time elapsed: 0.31 min
    * writing output
    Mapping chromosome chr17
    processing phenotype 850/1041    time elapsed: 0.34 min
    * writing output
    Mapping chromosome chr18
    processing phenotype 862/1041    time elapsed: 0.35 min
    * writing output
    Mapping chromosome chr19
    processing phenotype 967/1041    time elapsed: 0.37 min
    * writing output
    Mapping chromosome chr20
    processing phenotype 998/1041    time elapsed: 0.39 min
    * writing output
    Mapping chromosome chr21
    processing phenotype 1011/1041    time elapsed: 0.39 min
    * writing output
    Mapping chromosome chr22
    processing phenotype 1041/1041
    time elapsed: 0.40 min
    * writing output
done.
cis-QTL mapping: empirical p-values for phenotypes
  * 797 samples
  * 2678 phenotypes
  * 66 covariates
  * 6990104 variants
  * applying in-sample 0.1 MAF filter
  * cis-window: ±1,000,000
  * using seed 8888
  * checking phenotypes: 2678/2678
    ** dropping 292 phenotypes without variants in cis-window
  * computing permutations
    processing phenotype 2386/2386
  Time elapsed: 7.28 min
done.
cis-QTL mapping: nominal associations for all variant-phenotype pairs
  * 797 samples
  * 2678 phenotypes
  * 66 covariates
  * 6990104 variants
  * applying in-sample 0.1 MAF filter
  * cis-window: ±1,000,000
  * checking phenotypes: 2678/2678
    ** dropping 292 phenotypes without variants in cis-window
  * Computing associations
    Mapping chromosome chr1
    processing phenotype 119/2386    time elapsed: 0.02 min
    * writing output
    Mapping chromosome chr2
    processing phenotype 305/2386    time elapsed: 0.07 min
    * writing output
    Mapping chromosome chr3
    processing phenotype 479/2386    time elapsed: 0.12 min
    * writing output
    Mapping chromosome chr4
    processing phenotype 541/2386    time elapsed: 0.15 min
    * writing output
    Mapping chromosome chr5
    processing phenotype 643/2386    time elapsed: 0.17 min
    * writing output
    Mapping chromosome chr6
    processing phenotype 792/2386    time elapsed: 0.29 min
    * writing output
    Mapping chromosome chr7
    processing phenotype 932/2386    time elapsed: 0.36 min
    * writing output
    Mapping chromosome chr8
    processing phenotype 1016/2386    time elapsed: 0.39 min
    * writing output
    Mapping chromosome chr9
    processing phenotype 1108/2386    time elapsed: 0.42 min
    * writing output
    Mapping chromosome chr10
    processing phenotype 1165/2386    time elapsed: 0.44 min
    * writing output
    Mapping chromosome chr11
    processing phenotype 1326/2386    time elapsed: 0.48 min
    * writing output
    Mapping chromosome chr12
    processing phenotype 1486/2386    time elapsed: 0.52 min
    * writing output
    Mapping chromosome chr13
    processing phenotype 1535/2386    time elapsed: 0.55 min
    * writing output
    Mapping chromosome chr14
    processing phenotype 1636/2386    time elapsed: 0.57 min
    * writing output
    Mapping chromosome chr15
    processing phenotype 1724/2386    time elapsed: 0.61 min
    * writing output
    Mapping chromosome chr16
    processing phenotype 1835/2386    time elapsed: 0.64 min
    * writing output
    Mapping chromosome chr17
    processing phenotype 2021/2386    time elapsed: 0.75 min
    * writing output
    Mapping chromosome chr18
    processing phenotype 2058/2386    time elapsed: 0.80 min
    * writing output
    Mapping chromosome chr19
    processing phenotype 2226/2386    time elapsed: 0.85 min
    * writing output
    Mapping chromosome chr20
    processing phenotype 2300/2386    time elapsed: 0.88 min
    * writing output
    Mapping chromosome chr21
    processing phenotype 2332/2386    time elapsed: 0.92 min
    * writing output
    Mapping chromosome chr22
    processing phenotype 2386/2386
    time elapsed: 0.94 min
    * writing output
done.
cis-QTL mapping: empirical p-values for phenotypes
  * 815 samples
  * 8545 phenotypes
  * 66 covariates
  * 6990104 variants
  * applying in-sample 0.1 MAF filter
  * cis-window: ±1,000,000
  * using seed 8888
  * checking phenotypes: 8545/8545
    ** dropping 872 phenotypes without variants in cis-window
  * computing permutations
    processing phenotype 7673/7673
  Time elapsed: 21.11 min
done.
cis-QTL mapping: nominal associations for all variant-phenotype pairs
  * 815 samples
  * 8545 phenotypes
  * 66 covariates
  * 6990104 variants
  * applying in-sample 0.1 MAF filter
  * cis-window: ±1,000,000
  * checking phenotypes: 8545/8545
    ** dropping 872 phenotypes without variants in cis-window
  * Computing associations
    Mapping chromosome chr1
    processing phenotype 385/7673    time elapsed: 0.08 min
    * writing output
    Mapping chromosome chr2
    processing phenotype 991/7673    time elapsed: 0.31 min
    * writing output
    Mapping chromosome chr3
    processing phenotype 1480/7673    time elapsed: 0.66 min
    * writing output
    Mapping chromosome chr4
    processing phenotype 1683/7673    time elapsed: 0.90 min
    * writing output
    Mapping chromosome chr5
    processing phenotype 1987/7673    time elapsed: 1.10 min
    * writing output
    Mapping chromosome chr6
    processing phenotype 2456/7673    time elapsed: 1.59 min
    * writing output
    Mapping chromosome chr7
    processing phenotype 2902/7673    time elapsed: 2.47 min
    * writing output
    Mapping chromosome chr8
    processing phenotype 3197/7673    time elapsed: 2.91 min
    * writing output
    Mapping chromosome chr9
    processing phenotype 3542/7673    time elapsed: 3.28 min
    * writing output
    Mapping chromosome chr10
    processing phenotype 3739/7673    time elapsed: 3.61 min
    * writing output
    Mapping chromosome chr11
    processing phenotype 4242/7673    time elapsed: 3.91 min
    * writing output
    Mapping chromosome chr12
    processing phenotype 4732/7673    time elapsed: 4.34 min
    * writing output
    Mapping chromosome chr13
    processing phenotype 4868/7673    time elapsed: 4.75 min
    * writing output
    Mapping chromosome chr14
    processing phenotype 5183/7673    time elapsed: 4.91 min
    * writing output
    Mapping chromosome chr15
    processing phenotype 5451/7673    time elapsed: 5.22 min
    * writing output
    Mapping chromosome chr16
    processing phenotype 5859/7673    time elapsed: 5.51 min
    * writing output
    Mapping chromosome chr17
    processing phenotype 6403/7673    time elapsed: 5.92 min
    * writing output
    Mapping chromosome chr18
    processing phenotype 6522/7673    time elapsed: 6.27 min
    * writing output
    Mapping chromosome chr19
    processing phenotype 7132/7673    time elapsed: 6.50 min
    * writing output
    Mapping chromosome chr20
    processing phenotype 7365/7673    time elapsed: 6.98 min
    * writing output
    Mapping chromosome chr21
    processing phenotype 7453/7673    time elapsed: 7.19 min
    * writing output
    Mapping chromosome chr22
    processing phenotype 7673/7673
    time elapsed: 7.31 min
    * writing output
done.
cis-QTL mapping: empirical p-values for phenotypes
  * 813 samples
  * 4827 phenotypes
  * 66 covariates
  * 6990104 variants
  * applying in-sample 0.1 MAF filter
  * cis-window: ±1,000,000
  * using seed 8888
  * checking phenotypes: 4827/4827
    ** dropping 480 phenotypes without variants in cis-window
  * computing permutations
    processing phenotype 4347/4347
  Time elapsed: 12.94 min
done.
cis-QTL mapping: nominal associations for all variant-phenotype pairs
  * 813 samples
  * 4827 phenotypes
  * 66 covariates
  * 6990104 variants
  * applying in-sample 0.1 MAF filter
  * cis-window: ±1,000,000
  * checking phenotypes: 4827/4827
    ** dropping 480 phenotypes without variants in cis-window
  * Computing associations
    Mapping chromosome chr1
    processing phenotype 221/4347    time elapsed: 0.05 min
    * writing output
    Mapping chromosome chr2